title: Documentation
email: ''
description: >-
  Rawsec's CyberSecurity Inventory documentation
baseurl: "/docs/"
url: "https://inventory.raw.pm/"
twitter_username: rawsec_cyber

# Build settings
theme: just-the-docs
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# just-the-docs theme config - https://just-the-docs.com/docs/configuration/
logo: "/assets/images/rawsec_logo_dark_355x286.svg"
favicon_ico: "/assets/images/favicon/favicon.ico"
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false
aux_links:
  "Gitlab":
    - "https://gitlab.com/rawsec/rawsec-cybersecurity-list"
heading_anchors: true
nav_external_links:
color_scheme: rawsec

sass:
  quiet_deps: true # https://github.com/just-the-docs/just-the-docs/issues/1541
  silence_deprecations: ['import'] # https://github.com/just-the-docs/just-the-docs/issues/1607
